error: 24 -> 8 bytes
Since `Error` is by definition not the happy path, some optimizations
could be made. It's now a pointer-sized struct owning a `strdup`'d value
of `SDL_GetError`. This means that usage of it will probably incur a
`strlen`, but that would`ve unconditionally happened before as well, and
the capacity wasn't needed at all.